on:
  pull_request:
    branches:
      - main
    types: ["closed"]

jobs:
  cherry_pick_release_stable:
    runs-on: ubuntu-latest
    name: Cherry pick into release-stable
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick action
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release_v1.0
          committer: openhab-bot <info@openhab.org>
          labels: |
            cherry-pick
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
